[package]
name = "roast"
version = "0.1.0"
authors = ["Francesco Pasa <francescopasa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2"
uuid = "0.8.1"

#[profile.test]
#opt-level = 3